# Generated by Django 5.2.4 on 2025-07-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ropa', 'Ropa'), ('peleria', 'Peleria'), ('cables', 'Cables'), ('herramientas', 'Herramientas'), ('juguetes', 'Juguetes'), ('papeleria', 'Papeleria'), ('electronica', 'Electronica')], max_length=50)),
                ('tamanio', models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='objetos/')),
            ],
        ),
        migrations.CreateModel(
            name='Cajon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidadMaxima', models.IntegerField()),
                ('objetos', models.ManyToManyField(related_name='cajones', to='sistema.objeto')),
            ],
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('crear_cajon', 'Crear Cajón'), ('agregar_objeto', 'Agregar Objeto'), ('eliminar_objeto', 'Eliminar Objeto'), ('modificar_cajon', 'Modificar Cajón'), ('modificar_objeto', 'Modificar Objeto')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cajon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='sistema.cajon')),
                ('objetosAfectados', models.ManyToManyField(blank=True, related_name='acciones', to='sistema.objeto')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
