# Generated by Django 5.2 on 2025-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='tipo',
            field=models.CharField(choices=[('crear_cajon', 'Crear Cajón'), ('agregar_objeto', 'Agregar Objeto'), ('eliminar_objeto', 'Eliminar Objeto'), ('modificar_cajon', 'Modificar Cajón'), ('modificar_objeto', 'Modificar Objeto'), ('visualizar_caja', 'Visualizar Caja'), ('organizar_caja', 'Organizar Caja')], max_length=50),
        ),
    ]
