# Generated by Django 5.2 on 2025-07-31 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accion',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Acción', 'verbose_name_plural': 'Acciones'},
        ),
        migrations.AddField(
            model_name='accion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accion',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accion',
            name='cajon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='sistema.cajon'),
        ),
        migrations.AlterField(
            model_name='accion',
            name='tipo',
            field=models.CharField(choices=[('crear_cajon', 'Crear Cajón'), ('agregar_objeto', 'Agregar Objeto'), ('eliminar_objeto', 'Eliminar Objeto'), ('modificar_cajon', 'Modificar Cajón'), ('modificar_objeto', 'Modificar Objeto')], max_length=50),
        ),
    ]
